steps:
  - name: 'gcr.io/kaniko-project/executor'
    args:
      - --dockerfile=Dockerfile.neo4j
      - --context=.
      - --destination=${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_NEO4J_VERSION}

substitutions:
  _NEO4J_VERSION: $NEO4J_VERSION
  _GCP_PROJECT_ID: $GCP_PROJECT_ID
  _GCP_REGION: $GCP_REGION
  _REPO_NAME: $REPO_NAME
  _IMAGE_NAME: $IMAGE_NAME

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'